/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alesharik_adhoc_AdHocNetwork_SignalQuality */

#ifndef _Included_com_alesharik_adhoc_AdHocNetwork_SignalQuality
#define _Included_com_alesharik_adhoc_AdHocNetwork_SignalQuality
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
