/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alesharik_adhoc_AdHocInterface */

#ifndef _Included_com_alesharik_adhoc_AdHocInterface
#define _Included_com_alesharik_adhoc_AdHocInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alesharik_adhoc_AdHocInterface
 * Method:    getActiveNetwork
 * Signature: ()Lcom/alesharik/adhoc/AdHocNetwork;
 */
JNIEXPORT jobject JNICALL Java_com_alesharik_adhoc_AdHocInterface_getActiveNetwork
  (JNIEnv *, jobject);

/*
 * Class:     com_alesharik_adhoc_AdHocInterface
 * Method:    getDeviceSignature
 * Signature: ()Ljava/util/UUID;
 */
JNIEXPORT jobject JNICALL Java_com_alesharik_adhoc_AdHocInterface_getDeviceSignature
  (JNIEnv *, jobject);

/*
 * Class:     com_alesharik_adhoc_AdHocInterface
 * Method:    getFriendlyName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_alesharik_adhoc_AdHocInterface_getFriendlyName
  (JNIEnv *, jobject);

/*
 * Class:     com_alesharik_adhoc_AdHocInterface
 * Method:    getNetworks
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_alesharik_adhoc_AdHocInterface_getNetworks
  (JNIEnv *, jobject);

/*
 * Class:     com_alesharik_adhoc_AdHocInterface
 * Method:    getSecuritySettings
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_alesharik_adhoc_AdHocInterface_getSecuritySettings
  (JNIEnv *, jobject);

/*
 * Class:     com_alesharik_adhoc_AdHocInterface
 * Method:    getStatus
 * Signature: ()Lcom/alesharik/adhoc/ConnectionStatus;
 */
JNIEXPORT jobject JNICALL Java_com_alesharik_adhoc_AdHocInterface_getStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_alesharik_adhoc_AdHocInterface
 * Method:    isAdHocSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_alesharik_adhoc_AdHocInterface_isAdHocSupported
  (JNIEnv *, jobject);

/*
 * Class:     com_alesharik_adhoc_AdHocInterface
 * Method:    isDot11d
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_alesharik_adhoc_AdHocInterface_isDot11d
  (JNIEnv *, jobject);

/*
 * Class:     com_alesharik_adhoc_AdHocInterface
 * Method:    isRadioOn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_alesharik_adhoc_AdHocInterface_isRadioOn
  (JNIEnv *, jobject);

/*
 * Class:     com_alesharik_adhoc_AdHocInterface
 * Method:    register
 * Signature: (Lcom/alesharik/adhoc/AdHocInterface/Sink;)V
 */
JNIEXPORT void JNICALL Java_com_alesharik_adhoc_AdHocInterface_register
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_alesharik_adhoc_AdHocInterface
 * Method:    unregister
 * Signature: (Lcom/alesharik/adhoc/AdHocInterface/Sink;)V
 */
JNIEXPORT void JNICALL Java_com_alesharik_adhoc_AdHocInterface_unregister
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_alesharik_adhoc_AdHocInterface
 * Method:    clean
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_alesharik_adhoc_AdHocInterface_clean
  (JNIEnv *, jobject);

/*
 * Class:     com_alesharik_adhoc_AdHocInterface
 * Method:    init
 * Signature: (Ljava/util/UUID;)V
 */
JNIEXPORT void JNICALL Java_com_alesharik_adhoc_AdHocInterface_init
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
