/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_alesharik_adhoc_AdHocManager */

#ifndef _Included_com_alesharik_adhoc_AdHocManager
#define _Included_com_alesharik_adhoc_AdHocManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_alesharik_adhoc_AdHocManager
 * Method:    commit
 * Signature: (Lcom/alesharik/adhoc/AdHocNetwork;ZZ)Lcom/alesharik/adhoc/AdHocNetwork;
 */
JNIEXPORT jobject JNICALL Java_com_alesharik_adhoc_AdHocManager_commit
  (JNIEnv *, jclass, jobject, jboolean, jboolean);

/*
 * Class:     com_alesharik_adhoc_AdHocManager
 * Method:    createNetwork
 * Signature: (Ljava/lang/String;Ljava/lang/String;JLcom/alesharik/adhoc/AdHocInterface;Lcom/alesharik/adhoc/security/SecuritySettings;Ljava/util/UUID;)Lcom/alesharik/adhoc/AdHocNetwork;
 */
JNIEXPORT jobject JNICALL Java_com_alesharik_adhoc_AdHocManager_createNetwork
  (JNIEnv *, jclass, jstring, jstring, jlong, jobject, jobject, jobject);

/*
 * Class:     com_alesharik_adhoc_AdHocManager
 * Method:    getInterfaces
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_alesharik_adhoc_AdHocManager_getInterfaces
  (JNIEnv *, jclass);

/*
 * Class:     com_alesharik_adhoc_AdHocManager
 * Method:    getNetworks
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_alesharik_adhoc_AdHocManager_getNetworks
  (JNIEnv *, jclass);

/*
 * Class:     com_alesharik_adhoc_AdHocManager
 * Method:    getNetwork
 * Signature: (Ljava/util/UUID;)Lcom/alesharik/adhoc/AdHocNetwork;
 */
JNIEXPORT jobject JNICALL Java_com_alesharik_adhoc_AdHocManager_getNetwork
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_alesharik_adhoc_AdHocManager
 * Method:    registerSink
 * Signature: (Lcom/alesharik/adhoc/AdHocManager/Sink;)V
 */
JNIEXPORT void JNICALL Java_com_alesharik_adhoc_AdHocManager_registerSink
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_alesharik_adhoc_AdHocManager
 * Method:    unregisterSink
 * Signature: (Lcom/alesharik/adhoc/AdHocManager/Sink;)V
 */
JNIEXPORT void JNICALL Java_com_alesharik_adhoc_AdHocManager_unregisterSink
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
